### ISSUE TITLE
Search 기능 개선 건

### ISSUE THREAD

**Issue by JunhoYeo** [Juneyoung-Kang/hello-2018-homepage#1]
페이지의 Search 아이콘을 클릭했을 때 나타나는 검색창을 보고 키보드 입력을 하면 인식되지 않고,
다시 한 번 검색창을 클릭해 줘야 입력을 받는 부분이 있습니다.
페이지의 Search 아이콘을 클릭했을 때 나타나는 검색창에 focus 이벤트를 발생시켜서
바로 키보드 입력을 받을 수 있도록 하시는 게 어떨지 건의드립니다:)
아래에 업로드한 이미지를 참고하시면 이해가 쉬우실 것 같습니다. 감사합니다!
![image](https://user-images.githubusercontent.com/32605822/34648810-c67a9756-f3e4-11e7-83b6-ec658b09d726.png)

**Comment by Juneyoung-Kang** [comment]
확인했습니다.

해당 input 태그에 onclick="document.search_form.q.focus()"를 줘서 해결했습니다.

다음 커밋에서는 업데이트 될 예정입니다.

감사합니다.
